language: csharp
dotnet: 2.1.504
mono: none
dist: trusty
jobs:
    include:
        - stage: test
          script: dotnet test
        - stage: deploy
          script: dotnet pack src/Mailjet.SimpleClient/Mailjet.SimpleClient.csproj -c Release -p:PackageVersion=$TRAVIS_TAG
          deploy:
            skip_cleanup: true
            provider: script
            script: dotnet nuget push src/Mailjet.SimpleClient/bin/Release/Mailjet.*.nupkg --api-key $NUGET_API_KEY
stages:
 - test
 - name: deploy
   if: branch = master AND tag =~ ^(\d+\.)?(\d+\.)?(\*|\d+)(-\D+\.?\d+)?$